CREATE TABLE CAR(
                    ID SERIAL NOT NULL PRIMARY KEY,
                    MANUFACTURER_NAME TEXT NOT NULL,
                    MODEL_NAME TEXT NOT NULL,
                    NUMBER_OF_SEATS INTEGER NOT NULL
);

CREATE TABLE USERS(
                      ID SERIAL NOT NULL PRIMARY KEY,
                      EMAIL TEXT NOT NULL UNIQUE,
                      PHONE_NUMBER TEXT NOT NULL UNIQUE,
                      PASSWORD TEXT NOT NULL,
                      FIRST_NAME TEXT NOT NULL UNIQUE,
                      LAST_NAME TEXT NOT NULL UNIQUE,
                      ROLE TEXT NOT NULL
);

CREATE TABLE TRIPS (
                       ID SERIAL NOT NULL PRIMARY KEY,
                       START TEXT NOT NULL,
                       "END" TEXT NOT NULL,
                       DRIVER_ID SERIAL NOT NULL,
                       CONSTRAINT DRIVER_ID_CONSTRAINT FOREIGN KEY(DRIVER_ID) REFERENCES USERS(ID)
);

ALTER TABLE USERS ADD COLUMN CAR_ID SERIAL NOT NULL;
ALTER TABLE USERS ADD CONSTRAINT CAR_ID_CONSTRAINT FOREIGN KEY(CAR_ID) REFERENCES CAR(ID);

ALTER TABLE TRIPS ADD COLUMN PASSENGER_IDS INT[] NOT NULL;
