spring:
  datasource:
    url: jdbc:postgresql://ec2-50-16-221-180.compute-1.amazonaws.com:5432/d9c3hcfj92pl7u
    username: robgzcyipdtnnf
    password: cec0cc436f89d0689dd26ee8eb8afed5062d2280f9e564f5d236dbd731954845
    driver-class-name: org.postgresql.Driver
